name: RUN SHIPPING PARSER

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          PFSH_USERNAME: ${{ secrets.PFSH_USERNAME }}
          PFSH_PASSWORD: ${{ secrets.PFSH_PASSWORD }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          HOST: ${{ vars.HOST }}
          LOG_FILE: ${{ vars.LOG_FILE }}
          SHOP_NAME: ${{ vars.SHOP_NAME }}
          SHIPPING_FILE: ${{ vars.SHIPPING_FILE }}
        run: python shipping_update.py
